pub mod consumer;
mod dump;
pub mod generator;
pub mod odin_generator;
use consumer::{AstConsumer, RecBinding};
pub use dump::*;

pub type Node = clang_ast::Node<consumer::Item>;
use std::io::Write;
use std::fmt;

struct Indent(u32);

impl fmt::Display for Indent {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        for _ in 0..self.0 {
            f.write_str("    ")?;
        }

        Ok(())
    }
}


/// The variable name of `PodStructGen` in the structgen program
const SG: &str = "sg";
/// The name of the macro used to calculate a field's offset in the structgen program
const UOF: &str = "unsafe_offsetof";

/// Generates the structgen `main` function, which is used to generate
/// the the POD types for C and Rust and guarantee their fields are
/// appropriately sized and aligned so they can be interchanged
pub fn generate_structgen(
    ast: &AstConsumer<'_>,
    out: &mut impl Write,
) -> anyhow::Result<()> {
    // Preamble
    {
        // Get access to all of the PhysX types we're retrieving the layout for
        writeln!(out, "// Automatically generated by pxbind")?;
        writeln!(out, r#"#include "PxPhysicsAPI.h""#)?;
        writeln!(out, "\nusing namespace physx;")?;

        // Macro used to get the offset of each public field that the PODs
        // expose
        writeln!(
            out,
            "\n#define {UOF}(st, m) ((size_t) ( (char *)&((st *)(0))->m - (char *)0 ))"
        )?;
        // The header that contains the implementation of PodStructGen
        writeln!(out, r#"#include "structgen.hpp""#)?;
        writeln!(out, "\nint main() {{")?;
    }

    let indent = Indent(1);
    writeln!(out, "{indent}PodStructGen {SG};")?;

    let mut acc = String::new();
    for rec in ast.recs.iter() {
        acc.clear();


        match rec {
            RecBinding::Def(def) => def.emit_structgen(&mut acc, 1),
            RecBinding::Forward(forward) => forward.emit_structgen(&mut acc, 1),
        }
        writeln!(out, "{acc}")?;
    }

    writeln!(out, "{indent}{SG}.finish();\n}}")?;

    Ok(())
}

pub fn generate_cpp(ast: &AstConsumer, w: &mut impl Write) {

}
